"""
backend/tasks/reports.py
Scheduled Job — Monthly Doctor Activity Report
  Runs on the 1st of every month at 06:00.
  For every active doctor, generates an HTML report of the previous month's
  appointments, treatments, and diagnosis summary, then emails it.
"""

import logging
from datetime import date, datetime
from dateutil.relativedelta import relativedelta
from celery_worker import celery
from flask import current_app, render_template_string
from models import Doctor, Appointment, Treatment, User

logger = logging.getLogger(__name__)


# ── HTML Report Template ────────────────────────

REPORT_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8"/>
<style>
  body { font-family: Arial, sans-serif; color: #333; margin: 0; padding: 24px; }
  h1   { color: #0d6efd; font-size: 22px; border-bottom: 2px solid #0d6efd; padding-bottom: 8px; }
  h2   { color: #444; font-size: 16px; margin-top: 28px; }
  .meta { color: #666; font-size: 13px; margin-bottom: 20px; }
  .stats { display: flex; gap: 20px; margin-bottom: 24px; flex-wrap: wrap; }
  .stat-card { border: 1px solid #dee2e6; border-radius: 8px; padding: 14px 20px;
               min-width: 120px; text-align: center; }
  .stat-card .num  { font-size: 28px; font-weight: bold; color: #0d6efd; }
  .stat-card .lbl  { font-size: 12px; color: #888; margin-top: 4px; }
  table { width: 100%; border-collapse: collapse; font-size: 13px; margin-top: 10px; }
  th    { background: #0d6efd; color: #fff; padding: 8px 12px; text-align: left; }
  td    { padding: 8px 12px; border-bottom: 1px solid #dee2e6; vertical-align: top; }
  tr:nth-child(even) td { background: #f8f9fa; }
  .badge-completed { background:#198754; color:#fff; padding:2px 8px;
                     border-radius:12px; font-size:11px; }
  .badge-cancelled { background:#dc3545; color:#fff; padding:2px 8px;
                     border-radius:12px; font-size:11px; }
  .badge-booked    { background:#0d6efd; color:#fff; padding:2px 8px;
                     border-radius:12px; font-size:11px; }
  .footer { margin-top: 40px; font-size: 12px; color: #aaa;
            border-top: 1px solid #dee2e6; padding-top: 12px; }
</style>
</head>
<body>

<h1>🏥 Monthly Activity Report</h1>
<div class="meta">
  <strong>Doctor:</strong> Dr. {{ doctor_name }}<br>
  <strong>Specialization:</strong> {{ specialization }}<br>
  <strong>Department:</strong> {{ department }}<br>
  <strong>Report Period:</strong> {{ month_name }} {{ year }}<br>
  <strong>Generated:</strong> {{ generated_at }}
</div>

<h2>📊 Summary</h2>
<div class="stats">
  <div class="stat-card">
    <div class="num">{{ total }}</div>
    <div class="lbl">Total Appointments</div>
  </div>
  <div class="stat-card">
    <div class="num" style="color:#198754;">{{ completed }}</div>
    <div class="lbl">Completed</div>
  </div>
  <div class="stat-card">
    <div class="num" style="color:#dc3545;">{{ cancelled }}</div>
    <div class="lbl">Cancelled</div>
  </div>
  <div class="stat-card">
    <div class="num" style="color:#0d6efd;">{{ booked }}</div>
    <div class="lbl">Still Booked</div>
  </div>
  <div class="stat-card">
    <div class="num">{{ unique_patients }}</div>
    <div class="lbl">Unique Patients</div>
  </div>
</div>

<h2>📋 Appointment Details</h2>
{% if appointments %}
<table>
  <thead>
    <tr>
      <th>#</th>
      <th>Date</th>
      <th>Patient</th>
      <th>Time Slot</th>
      <th>Visit Type</th>
      <th>Status</th>
      <th>Diagnosis</th>
      <th>Prescription</th>
      <th>Next Visit</th>
    </tr>
  </thead>
  <tbody>
    {% for a in appointments %}
    <tr>
      <td>{{ loop.index }}</td>
      <td>{{ a.date }}</td>
      <td>{{ a.patient_name }}</td>
      <td>{{ a.time_slot }}</td>
      <td>{{ a.visit_type }}</td>
      <td>
        <span class="badge-{{ a.status | lower }}">{{ a.status }}</span>
      </td>
      <td>{{ a.diagnosis or '—' }}</td>
      <td>{{ a.prescription or '—' }}</td>
      <td>{{ a.next_visit or '—' }}</td>
    </tr>
    {% endfor %}
  </tbody>
</table>
{% else %}
<p style="color:#888;">No appointments in this period.</p>
{% endif %}

{% if top_diagnoses %}
<h2>🔬 Top Diagnoses This Month</h2>
<table style="max-width:500px;">
  <thead><tr><th>Diagnosis</th><th>Count</th></tr></thead>
  <tbody>
    {% for d in top_diagnoses %}
    <tr><td>{{ d.name }}</td><td>{{ d.count }}</td></tr>
    {% endfor %}
  </tbody>
</table>
{% endif %}

<div class="footer">
  This report was automatically generated by HMS V2 · {{ generated_at }}<br>
  For queries, contact your hospital administrator.
</div>
</body>
</html>
"""


def _build_report(doctor: Doctor, year: int, month: int) -> dict:
    """Build report data dict for a given doctor + month."""
    from calendar import month_name
    from collections import Counter

    first_day = date(year, month, 1)
    last_day  = (first_day + relativedelta(months=1)) - relativedelta(days=1)

    appointments = Appointment.query.filter(
        Appointment.doctor_id == doctor.id,
        Appointment.date >= first_day,
        Appointment.date <= last_day,
    ).order_by(Appointment.date).all()

    rows           = []
    diagnosis_list = []

    for a in appointments:
        diag = prescription = next_visit = None
        if a.treatment:
            diag       = a.treatment.diagnosis
            prescription = a.treatment.prescription
            next_visit = str(a.treatment.next_visit) if a.treatment.next_visit else None
            if diag:
                diagnosis_list.append(diag.strip().lower())

        rows.append({
            'date':         str(a.date),
            'patient_name': a.patient.full_name,
            'time_slot':    a.time_slot,
            'visit_type':   a.visit_type,
            'status':       a.status,
            'diagnosis':    diag,
            'prescription': prescription,
            'next_visit':   next_visit,
        })

    # Top diagnoses
    counter      = Counter(diagnosis_list)
    top_diagnoses= [{'name': k, 'count': v}
                    for k, v in counter.most_common(10)]

    unique_patients = len({a.patient_id for a in appointments})

    return {
        'doctor_name':     doctor.full_name,
        'specialization':  doctor.specialization,
        'department':      doctor.department.name if doctor.department else 'General',
        'month_name':      month_name[month],
        'year':            year,
        'generated_at':    datetime.utcnow().strftime('%d %b %Y, %H:%M UTC'),
        'total':           len(appointments),
        'completed':       sum(1 for a in appointments if a.status == 'Completed'),
        'cancelled':       sum(1 for a in appointments if a.status == 'Cancelled'),
        'booked':          sum(1 for a in appointments if a.status == 'Booked'),
        'unique_patients': unique_patients,
        'appointments':    rows,
        'top_diagnoses':   top_diagnoses,
    }


def _render_report_html(data: dict) -> str:
    return render_template_string(REPORT_TEMPLATE, **data)


def _email_report(doctor_email: str, doctor_name: str,
                  html_body: str, month_name: str, year: int):
    from flask_mail import Message
    from extensions import mail

    msg = Message(
        subject    = f"📋 Monthly Report — {month_name} {year}",
        recipients = [doctor_email],
        html       = html_body,
        sender     = current_app.config.get('MAIL_DEFAULT_SENDER', 'noreply@hms.com'),
    )
    mail.send(msg)


# ── Celery Task ─────────────────────────────────

@celery.task(name='tasks.reports.send_monthly_reports',
             bind=True, max_retries=2, default_retry_delay=600)
def send_monthly_reports(self):
    """
    Scheduled on the 1st of each month at 06:00.
    Generates and emails the previous month's activity report
    to every active doctor.
    """
    today    = date.today()
    prev     = today - relativedelta(months=1)
    year, month = prev.year, prev.month

    doctors = Doctor.query.join(User).filter(User.is_active == True).all()
    sent    = 0
    failed  = 0

    logger.info(f"[Monthly Reports] Generating for {month}/{year} — {len(doctors)} doctor(s).")

    for doctor in doctors:
        try:
            data      = _build_report(doctor, year, month)
            html_body = _render_report_html(data)
            _email_report(
                doctor_email = doctor.user.email,
                doctor_name  = doctor.full_name,
                html_body    = html_body,
                month_name   = data['month_name'],
                year         = year,
            )
            sent += 1
            logger.info(f"  ✓ Report sent → Dr. {doctor.full_name} <{doctor.user.email}>")
        except Exception as e:
            failed += 1
            logger.error(f"  ✗ Report failed for Dr. {doctor.full_name}: {e}")

    return {
        'period':  f"{month}/{year}",
        'sent':    sent,
        'failed':  failed,
        'completed_at': datetime.utcnow().isoformat(),
    }


@celery.task(name='tasks.reports.send_report_for_doctor')
def send_report_for_doctor(doctor_id: int, year: int, month: int):
    """
    On-demand: generate + email report for a specific doctor + period.
    Useful for admin manual triggers.
    """
    from calendar import month_name as mn
    doctor = Doctor.query.get(doctor_id)
    if not doctor:
        return {'error': f'Doctor {doctor_id} not found.'}

    data      = _build_report(doctor, year, month)
    html_body = _render_report_html(data)
    _email_report(
        doctor_email = doctor.user.email,
        doctor_name  = doctor.full_name,
        html_body    = html_body,
        month_name   = mn[month],
        year         = year,
    )
    return {'doctor': doctor.full_name, 'period': f"{month}/{year}", 'sent': True}
